# Generated by Codex on 2026-05-02

from django.db import migrations, models
import django.db.models.deletion


LOCATIONS = [
    ('Unspecified', 0),
    ('Kitchen', 1),
    ('Dining Room', 2),
    ('Living Room', 3),
    ('Family Room', 4),
    ('Bedroom', 5),
    ('Primary Bedroom', 6),
    ('Office', 7),
    ('Bathroom', 8),
    ('Laundry Room', 9),
    ('Garage', 10),
    ('Basement', 11),
    ('Attic', 12),
    ('Entryway', 13),
    ('Patio/Outdoor', 14),
    ('Storage', 15),
    ('Miscellaneous', 16),
]


def seed_locations(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    Asset = apps.get_model('core', 'Asset')

    fallback = None
    for name, order in LOCATIONS:
        location, _ = Location.objects.get_or_create(
            name=name,
            defaults={'display_order': order},
        )
        if name == 'Unspecified':
            fallback = location

    if fallback is not None:
        Asset.objects.filter(location__isnull=True).update(location=fallback)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_disclaimers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.location'),
        ),
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.location'),
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['category__display_order', 'location__display_order', 'name']},
        ),
    ]
